### PR TITLE
added column van_allowed to crossroads_transport

### PR DESCRIPTION
**Pull request by sunil-sharma**
schema.rb

### CODE REVIEW

**Comment by steveyken** [comment]
@swatijadhav @sunil-sharma thinking a bit more about that... what if the column was called 'enabled' - then we'd have a way to enable the 1/8 truck but not the 2/8 truck. Then the logic for Truck disabled would be that all entries were set to enabled=false. What do you think?

**Comment by swatijadhav** [comment]
Hi @steveyken,

Currently, the use-case behind adding the "is_van_allowed" column, is just to identify the 'Disable' option. Also at a time, only one crossroads-transport option is going to be available for single offer.

May be we are not getting the use-cases you are thinking of here.. 
We display all those records from 'crossroads_transports' table, do we want here to use 'enable' so that we can display only selected values? 
Correct us if we misunderstood it. Thanks.

**Comment by steveyken** [comment]
ok that's fine for now then. can always re-evaluate if the requirements change.

**Comment by sunil-sharma** [comment]
Thanks @Steve.

**Comment by swatijadhav** [comment]
Thanks @steveyken :+1:

**Pull request merged**
