### PR TITLE
bcc appointment email to staff and change from email id for booking

### PR DESCRIPTION
**Pull request by namrataukirde**
Hi Team,

This PR adds bcc for appointment email and changes from email id for same.

Please review.

Thanks

### CODE REVIEW

**Comment by namrataukirde** [comment]
Specs are already covered for this. We are setting bcc, from and to email ids from .nev so i don't think its valid to test that in specs.

**Comment by namrataukirde** [comment]
https://github.com/crossroads/api.goodcity/blob/master/spec/services/sendgrid_service_spec.rb

**Comment by steveyken** [comment]
got it thanks, sorry i took the PR as the whole thing and missed all the other work!

**Comment by namrataukirde** [comment]
No worries @steveyken  :)

**Pull request merged**
