### PR TITLE
external api-request authentication

### PR DESCRIPTION
**Pull request by steveyken**

### CODE REVIEW

**Comment by steveyken** [comment]
@swatijadhav This is good work. Only thing I'd recommend is to create a test spec to cover the `valid_user` cases in `spec/lib/warden/strategies/pin_strategy_spec.rb`

**Comment by swatijadhav** [comment]
Thanks @steveyken 
The test cases are updated here https://github.com/crossroads/api.goodcity/pull/153/files#diff-10
Shall we need to add something more specific?

**Comment by swatijadhav** [comment]
Thanks @steveyken :+1:

**Comment by swatijadhav** [comment]
Changes done for `api-write` permission for `stockit-user`.
@steveyken Can you please review it?
Thanks.

**Comment by steveyken** [comment]
Looks good to merge. Thank you!

**Pull request merged**
